# Generated by Django 3.0 on 2019-12-31 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full', models.CharField(max_length=120, null=True)),
                ('birthDate', models.DateField()),
                ('male', models.CharField(max_length=30)),
                ('feminine', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=50)),
                ('smartPhone', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
