# Generated by Django 3.0 on 2019-12-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191213_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeruser',
            old_name='userLogin',
            new_name='user_id',
        ),
    ]
