# Generated by Django 3.0 on 2019-12-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191213_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeruser',
            old_name='user_id',
            new_name='user',
        ),
    ]
