version: '2.2'
services: 
    ecommerce-mongodb:
        image: mongo 
        container_name: ecommerce-mongodb
        environment: 
            MONGO_INITDB_ROOT_USERNAME: ${}
            MONGO_INITDB_ROOT_PASSWORD: ${}
        volumes: 
            - "/home/jonas/mongodb:/var/lib/mongodb"
        ports: 
            - "27017:27017"
        networks: 
            - ecommerce-networks

    ecommercedatabase:
        image: postgres
        environment: 
            - POSTGRES_USER=${}
            - POSTGRES_PASSWORD=${}
            - POSTGRES_DB=${}
            - PYTHONUNBUFFERED=0
        container_name: ecommerce-db
        ports: 
            - "5433:5432"
        volumes: 
           - "/home/jonas/db:/var/lib/postgresql/data"
        networks: 
            - ecommerce-networks

    ecommerce:
        build: 
            dockerfile: dockerfile
            context: .
        image: jonasflorencio/ecommerce
        container_name: ecommerce
        volumes: 
            - ""
        ports: 
            - "8000:8000"
        networks: 
            - ecommerce-networks
        depends_on: 
            - "ecommercedatabase"
            - "ecommerce-mongodb"
        links: 
            - "ecommerce-mongodb"
            - "ecommercedatabase"

networks: 
    ecommerce-networks:
        driver: bridge