version: '2.2'
services: 
    ecommercedatabase:
        image: postgres
        environment: 
            - POSTGRES_USER=${NAME_USER_DB}
            - POSTGRES_PASSWORD=${PASSWORD_USER_DB}
            - POSTGRES_DB=${NAME_DATA_BASE}
        container_name: ecommerce-db
        ports: 
            - "5433:5432"
        volumes: 
           - "/home/jonas/db:/var/lib/postgresql/data"
        networks: 
            - ecommerce-networks

    ecommerce:
        build: 
            dockerfile: dockerfile
            context: .
        image: jonasflorencio/ecommerce
        container_name: ecommerce
        volumes: 
            - /home/jonas/Code/ecommerce:/home/jonas/Code
        ports: 
            - "8000:8000"
        networks: 
            - ecommerce-networks
        depends_on: 
            - "ecommercedatabase"
        links: 
            - "ecommercedatabase"

networks: 
    ecommerce-networks:
        driver: bridge